### ISSUE TITLE
New Sage 10 structure

### ISSUE THREAD

**Issue by catgofire** [Log1x/sage-svg#11]
The build directory has changed from `dist/` to `public/` in Sage 10, but the default here is still `dist/`. I know there's a ton of stuff you guys are updating, just wanted to leave this note here after fixing this for myself via the config file.

**Comment by Log1x** [comment]
Should be able to just change this to using the `Roots\public_path()` function. Just need to test on an old version of Acorn to make sure I don't have to push a major version.

**Comment by vdrnn** [comment]
@Log1x so I just tried to implement it within sage 10.0.0-beta.3. 

@catgofire can you post your fix maybe?

**Comment by catgofire** [comment]
@vdrnn Here's a pared down version of my `sage-theme/config/svg.php` file (create the file if it doesn't exist):

```php
<?php

use function Roots\base_path;

return [
    'path' => base_path('public/images/svg'),
];
```

Not sure if this is the proper way to do it, but it's been working for me for a year :)

**Comment by transcript-js** [comment]
Just in case: mine looks like this

```php
<?php

use function Roots\base_path;

return [

    'path' => base_path('public/assets'),

];
```
My svg directory is `/theme-name/resources/svg` (not a subdirectory but in parallel to `/images/`)

Dist: `/theme-name/public/assets/svg`

**Comment by Log1x** [comment]
https://github.com/Log1x/sage-svg/pull/13
