### ISSUE TITLE
@svg is not being parsed

### ISSUE THREAD

**Issue by purplefeel** [Log1x/sage-svg#12]
log1x/sage-svg version: v1.0.6
roots/sage: 10.0.0-beta

I installed `log1x/sage-svg` package using composer.
But the @svg directive is not being parsed and rendered as raw string on the webpage.
I also use `log1x/sage-directives` and their directives are being parsed well.

```
  @hassub('icon')
    @sub('icon')
    @svg(157)
  @endsub

```

![image](https://user-images.githubusercontent.com/45671430/146520734-ec192a6a-b76d-4147-8f97-c291c31c8729.png)

**Comment by purplefeel** [comment]
Also can I use something like this?
`@svg(@sub('icon'))`
That's what I need to finally achieve.

**Comment by purplefeel** [comment]
Hi again,

According to the documentation:
```
Blade Directive
Unless you require advance functionality from somewhere such as a Controller, the best way to use Sage SVG is with the Blade directive straight in your templates.

# Relative path (with dot notation) – resolves to `app/themes/<your theme>/dist/images/logo.svg` by default
@svg('images.logo')

# Absolute path from webroot with `w-32 h-auto` CSS classes and an aria-label
@svg('app/uploads/2019/07/logo.svg', 'w-32 h-auto', ['aria-label' => 'Logo'])
```

Raw PHP work.

```
{!! get_svg( ['id' => 157], 'w-56 h-auto') !!}
```
Can I use attachment ID for the directive as well?

```
@svg(['id' => 157], 'w-56 h-auto')
```

**Comment by Log1x** [comment]
> But the @svg directive is not being parsed and rendered as raw string on the webpage.

Weird. Have you tried running `wp acorn optimize:clear`?



> Also can I use something like this?
> `@svg(@sub('icon'))`

Unfortunately it's not possible to do directives inside of directives. You'd need to choose between `get_field` or `get_svg` for passing data.

> Can I use attachment ID for the directive as well?

I think so...

**Comment by purplefeel** [comment]
> Unfortunately it's not possible to do directives inside of directives. You'd need to choose between get_field or get_svg for passing data.


Got it. Thank you!

> Can I use attachment ID for the directive as well?
> 
> I think so...

Yeah I expected the same, but it actually doesn't work. It shows the raw text.

**Comment by farmerpaul** [comment]
@Log1x, thanks for the suggestion of using `wp acorn optimize:clear`, that seemed to do the trick. Although perhaps just restarting `yarn dev` would have as well, not sure… I ended up here because I was having the same experience as @purplefeel with the `@svg()` code being output verbatim, which never used to happen with previous versions of Sage 10. This seems to be new since they overhauled it to make use of Bud (among other things).

**Comment by strarsis** [comment]
@farmerpaul, @Log1x: This was extremely helpful! I already started to despair when I saw the dreaded, unparsed directive.

**Comment by robrecord** [comment]
Mine was not working - I had done the following:

```
wp acorn package:discover
wp acorn optimize:clear
```
and restarted `yarn dev`

Still an unparsed @svg directive

The problem was that I had installed it to bedrock's composer instead of sage. 

After moving it, I ran the above steps (`wp acorn package:discover` was crucial) then it worked.

**Comment by Awilson089** [comment]
@Log1x – Is it worth adding @robrecord's comment to the docs? It was useful to know and not everyone will check closed issues 🙂
