### ISSUE TITLE
All svgs on same page render as the first svg directive

### ISSUE THREAD

**Issue by samlinck** [Log1x/sage-svg#14]
In this case all svgs renders as the facebook icon. If I comment out the first, all the svgs render as the instagram icon. 
When looking into the public folder, the svgs are present.

```
    <a href="{{ get_field('facebook', 'options') }}" target="_blank">
        @svg('facebook', 'w-6 h-6')
    </a>

    <a href="{{ get_field('instagram', 'options') }}" target="_blank">
        @svg('instagram', 'w-6 h-6')
    </a>

    <a href="{{ get_field('twitter', 'options') }}" target="_blank">
        @svg('twitter', 'w-6 h-6')
    </a>

```

**Comment by transcript-js** [comment]
Hi, you're missing a closing single quote for all three size parameters (no idea if that's the reason, though, and no time to check).

**Comment by samlinck** [comment]
The single quote was indeed missing, but not the issue.. Was wrongly copied.

**Comment by samlinck** [comment]
The issue was with the svgs. They used the same id for the svg pattern.
