### ISSUE TITLE
svg not found - cache busting

### ISSUE THREAD

**Issue by eriteric** [Log1x/sage-svg#16]
Just started using sage10, so I'm not sure if this is a new feature or not, but when I run `yarn build` all images are appended with a cache busting suffix. @asset seems to handle this fine however @svg cannot find them once compiled for production, though it finds them after `yarn dev` just fine (when they do not have the suffixes).

**Comment by eriteric** [comment]
For now this worked: `@asset('images/svg/image.svg') `

**Comment by Log1x** [comment]
https://github.com/Log1x/sage-svg/blob/master/src/SageSvg.php#L82 should be making this work as intended. 🤔 Could you attempt to debug it a bit?

**Comment by eriteric** [comment]
Not sure how I resolved this, but it could have been related to the bud proxy

**Comment by marcbelletre** [comment]
Hi @Log1x,

I have the same issue. I originally put my icons in the `resources/images/icons`. When running `yarn build`, the icons were copied inside the `public/images/icons` directory with a random suffix which broke the `@svg` directive.  

The solution I found was to move the `icons` directory out of `resources/images` so it is not processed by Bud's `asset()` and update the path in the package config.

```php
<?php

return [

    'path' => resource_path('icons'),

    // ...
```

Maybe this should be added to the documentation?
