### ISSUE TITLE
if customer logic without manifest got exception

### ISSUE THREAD

**Issue by gerasart** [Log1x/sage-svg#20]
need fix

wp-content/themes/casinorix/vendor/log1x/sage-svg/src/SageSvg.php:81

```
    protected function get($image)
    {
        if (asset($image)->exists()) {
            return trim(
                asset($image)->contents()
            );
        }
```

need that scenario works without asset($image)->exists(), so u can add params to config that not use manifest.

**Comment by Log1x** [comment]
Not sure what you're asking. Open a PR if you need any changes.
