### ISSUE TITLE
get_svg doesn't accept arrays anymore

### ISSUE THREAD

**Issue by SergiArias** [Log1x/sage-svg#28]
get_svg should accept string|array, but it's set to accept only strings, and so, it's not possible to work with an id.

**Comment by Log1x** [comment]
Can you give an example of what you were doing? It's the same as [`SageSvg::render`](https://github.com/Log1x/sage-svg/blob/master/src/SageSvg.php#L31) and should be a dot notated path to the asset.

**Comment by SergiArias** [comment]
I think in the past it worked, but now it doesn't.

Example: an $img created with advanced custom fields:
`@svg($img)` doesn't work (this image is an array with "id" => "1234").
In the code I see the get_svg first parameter only accepts strings, but later on, it checks if it's an array and then gets the id. Just changing the parameter to accept string|array works again.

It's the functionality mentioned in the readme:

```markdown
## Usage

By default, the following paths are checked for your SVG (in order):

- If passed an array containing `id`, it is assumed to be a WordPress attachment and is ran through [`get_attached_file()`](https://developer.wordpress.org/reference/functions/get_attached_file).
```

I created the following pull request with the proposed change: https://github.com/Log1x/sage-svg/pull/29

**Comment by Log1x** [comment]
Totally see it on `SageSvg::resolvePath` now – very sorry about that! I hadn't personally used it for attachments before. Appreciate the PR.

**Comment by joshuafredrickson** [comment]
Would it be possible to get a release for this fix? I just realized the latest release predates this PR. 🙏

**Comment by Log1x** [comment]
> Would it be possible to get a release for this fix? I just realized the latest release predates this PR. 🙏

done! sorry about that

**Comment by joshuafredrickson** [comment]
Appreciate it! 🤙
