### ISSUE TITLE
Config not published when defining with --provider

### ISSUE THREAD

**Issue by tylerwiegand** [Log1x/sage-svg#5]
Could just be a problem with my setup, but when i use

```
wp acorn vendor:publish --provider='Log1x\SageSvg\SageSvgServiceProvider'
```
it APPEARS to function, but then I don't see the config file show up. If I just choose it through the prompt, it does generate the file.

The reason I say it might be my setup is because I had the same problem with the ACF Composer package, but I just copy/pasted from the documentation instead of tried to fix it.

This time I just tried without the --provider argument and it worked!

![image](https://user-images.githubusercontent.com/11890164/70563799-bdd78b80-1b43-11ea-89b7-e040e569b0a9.png)

**Comment by Log1x** [comment]
Can you try with double quotes on the provider?

```
wp acorn vendor:publish --provider="Log1x\SageSvg\SageSvgServiceProvider"
```

otherwise I'll have to see what's up later. It might be an issue in Acorn or something.

**Comment by tylerwiegand** [comment]
Just tested with the quotes, no dice unfortunately =\

**Comment by Log1x** [comment]
This is an Acorn/WP CLI issue that is being worked on upstream.
