### ISSUE TITLE
[Feature Request] Use SageSVG for acf-composer block icons!

### ISSUE THREAD

**Issue by tylerwiegand** [Log1x/sage-svg#6]
So while enjoying composing blocks A LOT, I can't help but want to use SageSVG's `get_svg()` with the Block `register()` icon.

So right now, in order to see the icon in the interface, I need to paste in the string of the SVG rather than use the beautiful helper function. I dug in a little and I think it has something to do with the `asset()` helper being used to resolve the path of the file, but also that `get_svg()` is returning an HTML element. I added a `get_svg_string()` but then ran into the asset() helper using the Filesystem as an issue.

THEN I went nuclear and tried just a plain `file_get_contents()` but the Block registers different in the view than the WP Admin (by design of course), so just to see if it would EVER work I threw in a gross if/then...and it DID work... but it's gross! Lol...

If you have an idea for some angle I can pursue for a PR, I'm out of ideas. I don't see how to use the configs path without including the Filesystem, but maybe I'm mistaken about what the actual problem is too.

Maybe there's even a 'no-duh' thing I can use for this situation and I'm just not aware of it... halp! =)

Images after the nuclear fix:
![image](https://user-images.githubusercontent.com/11890164/70568044-ecf1fb00-1b4b-11ea-9a14-bdd38e390c27.png)

![image](https://user-images.githubusercontent.com/11890164/70568056-f24f4580-1b4b-11ea-8464-317754d76510.png)

**Comment by Log1x** [comment]
does `asset('svg/brands/facebook.svg')->contents()` work? (assuming the svg is in `dist`)

**Comment by tylerwiegand** [comment]
Yeah this is part of what was confusing to me -- when I do
```
{{ \Roots\asset('svg/brands/facebook.svg')->contents() }}
```
on a page/in a block etc, I get the desired output
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"/></svg>
```
but when I do the same thing inside the Block file
```
'icon' => \Roots\asset('svg/brands/facebook.svg')->contents(),
```
I get a [nice big whoops screen](https://pastebin.com/TrQqecN7) (which I love seeing, but I couldn't figure out much from this one)

I didn't even try `asset()->contents()` but this IS the same error I was getting from attempting to `get_svg_string()` (my quick and dirty attempt at making this work)
